#ifndef _MODBUS_CONFIG
#define _MODBUS_CONFIG

#define CONFIG_MB_UART_PORT_NUM 2
#define CONFIG_MB_UART_BAUD_RATE 9600
#define CONFIG_MB_UART_RXD 20
#define CONFIG_MB_UART_TXD 4
#define CONFIG_MB_UART_RTS 19
#define CONFIG_MB_COMM_MODE_RTU y

#endif
